// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stream.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StreamPoint struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                int32    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamPoint) Reset()         { *m = StreamPoint{} }
func (m *StreamPoint) String() string { return proto.CompactTextString(m) }
func (*StreamPoint) ProtoMessage()    {}
func (*StreamPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{0}
}

func (m *StreamPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamPoint.Unmarshal(m, b)
}
func (m *StreamPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamPoint.Marshal(b, m, deterministic)
}
func (m *StreamPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamPoint.Merge(m, src)
}
func (m *StreamPoint) XXX_Size() int {
	return xxx_messageInfo_StreamPoint.Size(m)
}
func (m *StreamPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamPoint.DiscardUnknown(m)
}

var xxx_messageInfo_StreamPoint proto.InternalMessageInfo

func (m *StreamPoint) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StreamPoint) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type ReqStream struct {
	Pt                   *StreamPoint `protobuf:"bytes,1,opt,name=pt,proto3" json:"pt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReqStream) Reset()         { *m = ReqStream{} }
func (m *ReqStream) String() string { return proto.CompactTextString(m) }
func (*ReqStream) ProtoMessage()    {}
func (*ReqStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{1}
}

func (m *ReqStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqStream.Unmarshal(m, b)
}
func (m *ReqStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqStream.Marshal(b, m, deterministic)
}
func (m *ReqStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqStream.Merge(m, src)
}
func (m *ReqStream) XXX_Size() int {
	return xxx_messageInfo_ReqStream.Size(m)
}
func (m *ReqStream) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqStream.DiscardUnknown(m)
}

var xxx_messageInfo_ReqStream proto.InternalMessageInfo

func (m *ReqStream) GetPt() *StreamPoint {
	if m != nil {
		return m.Pt
	}
	return nil
}

type RespStream struct {
	Pt                   *StreamPoint `protobuf:"bytes,1,opt,name=pt,proto3" json:"pt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RespStream) Reset()         { *m = RespStream{} }
func (m *RespStream) String() string { return proto.CompactTextString(m) }
func (*RespStream) ProtoMessage()    {}
func (*RespStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{2}
}

func (m *RespStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespStream.Unmarshal(m, b)
}
func (m *RespStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespStream.Marshal(b, m, deterministic)
}
func (m *RespStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespStream.Merge(m, src)
}
func (m *RespStream) XXX_Size() int {
	return xxx_messageInfo_RespStream.Size(m)
}
func (m *RespStream) XXX_DiscardUnknown() {
	xxx_messageInfo_RespStream.DiscardUnknown(m)
}

var xxx_messageInfo_RespStream proto.InternalMessageInfo

func (m *RespStream) GetPt() *StreamPoint {
	if m != nil {
		return m.Pt
	}
	return nil
}

func init() {
	proto.RegisterType((*StreamPoint)(nil), "proto.StreamPoint")
	proto.RegisterType((*ReqStream)(nil), "proto.ReqStream")
	proto.RegisterType((*RespStream)(nil), "proto.RespStream")
}

func init() { proto.RegisterFile("stream.proto", fileDescriptor_bb17ef3f514bfe54) }

var fileDescriptor_bb17ef3f514bfe54 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8e, 0x31, 0x8e, 0x83, 0x30,
	0x10, 0x45, 0xd7, 0x08, 0x23, 0x31, 0xec, 0x4a, 0xbb, 0xa3, 0x2d, 0x50, 0x2a, 0xe4, 0x8a, 0x0a,
	0x08, 0x29, 0x72, 0x89, 0x14, 0x91, 0x39, 0x01, 0x21, 0x53, 0x20, 0x05, 0xec, 0x18, 0xc3, 0x95,
	0x72, 0xcd, 0x48, 0x76, 0x82, 0x52, 0x52, 0xcd, 0xcc, 0x93, 0xde, 0xfc, 0x0f, 0xdf, 0x93, 0x35,
	0xd4, 0x0e, 0x85, 0x36, 0xca, 0x2a, 0xe4, 0x6e, 0x88, 0x23, 0x24, 0x8d, 0xc3, 0x67, 0xd5, 0x8f,
	0x16, 0x11, 0xc2, 0xb1, 0x1d, 0x28, 0x65, 0x19, 0xcb, 0x63, 0xe9, 0x76, 0xfc, 0x07, 0xbe, 0xb4,
	0xb7, 0x99, 0xd2, 0x20, 0x63, 0x39, 0x97, 0xfe, 0x10, 0x25, 0xc4, 0x92, 0xee, 0xde, 0x45, 0x01,
	0x81, 0xb6, 0x4e, 0x4a, 0x6a, 0xf4, 0x01, 0xc5, 0xc7, 0x5b, 0x19, 0x68, 0x2b, 0x2a, 0x00, 0x49,
	0x93, 0xde, 0x6e, 0xd4, 0x0f, 0x06, 0x3f, 0x9e, 0x35, 0x64, 0x96, 0xbe, 0x23, 0x2c, 0x21, 0x3c,
	0xf5, 0x93, 0xc5, 0xdf, 0x97, 0xb1, 0x36, 0xd8, 0xfd, 0xad, 0xe4, 0x1d, 0x21, 0xbe, 0x2a, 0x86,
	0x7b, 0x88, 0x24, 0x75, 0xca, 0x5c, 0x37, 0x2a, 0x39, 0xc3, 0x1a, 0xb8, 0x54, 0xb3, 0xa5, 0xcd,
	0x46, 0xc5, 0x2e, 0x91, 0xe3, 0x87, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x93, 0x7f, 0x58, 0xdf,
	0x63, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StreamServiceClient is the client API for StreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StreamServiceClient interface {
	// 服务器端流 RPC
	List(ctx context.Context, in *ReqStream, opts ...grpc.CallOption) (StreamService_ListClient, error)
	// 客户端流  RPC
	Record(ctx context.Context, opts ...grpc.CallOption) (StreamService_RecordClient, error)
	// 双向流 RPC
	Route(ctx context.Context, opts ...grpc.CallOption) (StreamService_RouteClient, error)
}

type streamServiceClient struct {
	cc *grpc.ClientConn
}

func NewStreamServiceClient(cc *grpc.ClientConn) StreamServiceClient {
	return &streamServiceClient{cc}
}

func (c *streamServiceClient) List(ctx context.Context, in *ReqStream, opts ...grpc.CallOption) (StreamService_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StreamService_serviceDesc.Streams[0], "/proto.StreamService/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamServiceListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StreamService_ListClient interface {
	Recv() (*RespStream, error)
	grpc.ClientStream
}

type streamServiceListClient struct {
	grpc.ClientStream
}

func (x *streamServiceListClient) Recv() (*RespStream, error) {
	m := new(RespStream)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamServiceClient) Record(ctx context.Context, opts ...grpc.CallOption) (StreamService_RecordClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StreamService_serviceDesc.Streams[1], "/proto.StreamService/Record", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamServiceRecordClient{stream}
	return x, nil
}

type StreamService_RecordClient interface {
	Send(*ReqStream) error
	CloseAndRecv() (*RespStream, error)
	grpc.ClientStream
}

type streamServiceRecordClient struct {
	grpc.ClientStream
}

func (x *streamServiceRecordClient) Send(m *ReqStream) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamServiceRecordClient) CloseAndRecv() (*RespStream, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(RespStream)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamServiceClient) Route(ctx context.Context, opts ...grpc.CallOption) (StreamService_RouteClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StreamService_serviceDesc.Streams[2], "/proto.StreamService/Route", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamServiceRouteClient{stream}
	return x, nil
}

type StreamService_RouteClient interface {
	Send(*ReqStream) error
	Recv() (*RespStream, error)
	grpc.ClientStream
}

type streamServiceRouteClient struct {
	grpc.ClientStream
}

func (x *streamServiceRouteClient) Send(m *ReqStream) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamServiceRouteClient) Recv() (*RespStream, error) {
	m := new(RespStream)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamServiceServer is the server API for StreamService service.
type StreamServiceServer interface {
	// 服务器端流 RPC
	List(*ReqStream, StreamService_ListServer) error
	// 客户端流  RPC
	Record(StreamService_RecordServer) error
	// 双向流 RPC
	Route(StreamService_RouteServer) error
}

// UnimplementedStreamServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStreamServiceServer struct {
}

func (*UnimplementedStreamServiceServer) List(req *ReqStream, srv StreamService_ListServer) error {
	return status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedStreamServiceServer) Record(srv StreamService_RecordServer) error {
	return status.Errorf(codes.Unimplemented, "method Record not implemented")
}
func (*UnimplementedStreamServiceServer) Route(srv StreamService_RouteServer) error {
	return status.Errorf(codes.Unimplemented, "method Route not implemented")
}

func RegisterStreamServiceServer(s *grpc.Server, srv StreamServiceServer) {
	s.RegisterService(&_StreamService_serviceDesc, srv)
}

func _StreamService_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReqStream)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamServiceServer).List(m, &streamServiceListServer{stream})
}

type StreamService_ListServer interface {
	Send(*RespStream) error
	grpc.ServerStream
}

type streamServiceListServer struct {
	grpc.ServerStream
}

func (x *streamServiceListServer) Send(m *RespStream) error {
	return x.ServerStream.SendMsg(m)
}

func _StreamService_Record_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamServiceServer).Record(&streamServiceRecordServer{stream})
}

type StreamService_RecordServer interface {
	SendAndClose(*RespStream) error
	Recv() (*ReqStream, error)
	grpc.ServerStream
}

type streamServiceRecordServer struct {
	grpc.ServerStream
}

func (x *streamServiceRecordServer) SendAndClose(m *RespStream) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamServiceRecordServer) Recv() (*ReqStream, error) {
	m := new(ReqStream)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _StreamService_Route_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamServiceServer).Route(&streamServiceRouteServer{stream})
}

type StreamService_RouteServer interface {
	Send(*RespStream) error
	Recv() (*ReqStream, error)
	grpc.ServerStream
}

type streamServiceRouteServer struct {
	grpc.ServerStream
}

func (x *streamServiceRouteServer) Send(m *RespStream) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamServiceRouteServer) Recv() (*ReqStream, error) {
	m := new(ReqStream)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _StreamService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.StreamService",
	HandlerType: (*StreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _StreamService_List_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Record",
			Handler:       _StreamService_Record_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Route",
			Handler:       _StreamService_Route_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "stream.proto",
}
